service:
  name: product-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: '2'

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-jest-plugin

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  stage: dev

  environment: 
    db_connect: ${file(/Users/alexander/Documents/Node_JS_AWS/shop-telethones-be/product-service/secret_ID)}


custom:
  jest:
    # You can pass jest options here
    # See details here: https://facebook.github.io/jest/docs/configuration.html
    # For instance, uncomment next line to enable code coverage
    # collectCoverage: true
    

functions:
  getProductsList:
    handler: getProductsList.get
    events:
    - http:
        method: get
        path: products
        cors: true
  getProductsById:
    handler: getProductsById.get
    events:
      - http:
          method: get
          path: /products/{productId}
          cors: true
          request: 
            parameters: 
              paths: 
                productId: true
  postProducts:
    handler: postProducts.post
    events:
      - http:
          method: post
          path: products
          cors: true

